spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # Don't not return the field to front end if it is empty.
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

