package com.zhihao.sell.VO;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import lombok.Data;

import java.util.List;

/**
 * Product VO (including category)
 */
@Data
public class ProductVO implements Serializable {
  // ID generated by plugin, which confirms it unique when serializing.
  private static final long serialVersionUID = 3038551413904374511L;
  // Using JsonProperty to transform the data to front end as "name"
  @JsonProperty("name")
  private String categoryName;

  // Using JsonProperty to transform the data to front end as "type"
  @JsonProperty("type")
  private Integer categoryType;

  // Using JsonProperty to transform the data to front end as "foods"
  @JsonProperty("foods")
  private List<ProductInfoVO> productInfoVOList;
}
