package com.zhihao.sell.VO;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Information about a product needed to transit to front end.
 * No need to transit stock info. Only send necessary info.
 */
@Data
public class ProductInfoVO implements Serializable {

  // ID generated by plugin, which confirms it unique when serializing.
  private static final long serialVersionUID = -5066554146148536447L;
  // Using JsonProperty to transform the data to front end as "id"
  @JsonProperty("id")
  private String productId;

  // Using JsonProperty to transform the data to front end as "name"
  @JsonProperty("name")
  private String productName;

  // Using JsonProperty to transform the data to front end as "price"
  @JsonProperty("price")
  private BigDecimal productPrice;

  // Using JsonProperty to transform the data to front end as "description"
  @JsonProperty("description")
  private String productDescription;

  // Using JsonProperty to transform the data to front end as "icon"
  @JsonProperty("icon")
  private String productIcon;
}
