package com.zhihao.sell.VO;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;
import lombok.Data;

/*
 * the outer object of http request (which will transform to front end)
 * ResultVO includes ProductVO, which then includes a list of ProductInfoVO.
 * Send to front end
 *
 * Serializable is used for cache
 * */
@Data
public class ResultVO<T> implements Serializable {

  // ID generated by plugin, which confirms it unique when serializing.
  private static final long serialVersionUID = 3494099586806121532L;
  /**
   * status code (0 is success).
   */
  private Integer code;

  /**
   * message.
   */
  private String msg;

  /**
   * detail (information transformed to front end).
   */
  private T data;
}
